/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista.componentesGraficos;


import java.awt.Color;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 *
 * @author Joel
 */
public class CurviLinearChart extends javax.swing.JPanel {

    /**
     * Creates new form panelGraficaBarra
     */
      
    public CurviLinearChart() {
        initComponents();
    chart.setTitle("Ventas");
    chart.addLegend("Día", Color.decode("#7722d4"), Color.decode("#bb91ea"));
    chart.addLegend("Semana", Color.decode("#5752D1"), Color.decode("#A2D9D9"));
    chart.addLegend("Mes", Color.decode("#6684a2"), Color.decode("#80a5ca"));
    setData();
    }
 private void setData() {

            chart.addData(new ModelChart("01", new double[]{30, 25, 32}));
            chart.addData(new ModelChart("02", new double[]{45, 32, 78}));
            chart.addData(new ModelChart("03", new double[]{54, 77, 92}));
            chart.addData(new ModelChart("04", new double[]{10, 05, 56}));
            chart.addData(new ModelChart("05", new double[]{98, 22, 12}));
            chart.addData(new ModelChart("06", new double[]{74, 27, 62}));
            chart.addData(new ModelChart("07", new double[]{26, 85, 06}));
            chart.addData(new ModelChart("10", new double[]{73, 64, 53}));
            chart.addData(new ModelChart("11", new double[]{83, 15, 32}));
            chart.addData(new ModelChart("12", new double[]{31, 72, 93}));
            chart.addData(new ModelChart("14", new double[]{53, 32, 98}));
            chart.addData(new ModelChart("15", new double[]{73, 61, 74}));
            
        

        // Iniciar la animación de la gráfica
        chart.start();

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelShadow2 = new vista.componentesGraficos.PanelShadow();
        chart = new vista.componentesGraficos.CurveLineChart();

        panelShadow2.setBackground(new java.awt.Color(155, 0, 232));
        panelShadow2.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        panelShadow2.setColorGradient(new java.awt.Color(16, 3, 17));
        panelShadow2.setGradientType(vista.componentesGraficos.PanelShadow.GradientType.VERTICAL);
        panelShadow2.setShadowOpacity(0.0F);
        panelShadow2.setShadowSize(1);
        panelShadow2.setShadowType(null);

        chart.setForeground(new java.awt.Color(255, 255, 255));
        chart.setFillColor(true);

        javax.swing.GroupLayout panelShadow2Layout = new javax.swing.GroupLayout(panelShadow2);
        panelShadow2.setLayout(panelShadow2Layout);
        panelShadow2Layout.setHorizontalGroup(
            panelShadow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chart, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
        );
        panelShadow2Layout.setVerticalGroup(
            panelShadow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chart, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelShadow2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelShadow2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private vista.componentesGraficos.CurveLineChart chart;
    private vista.componentesGraficos.PanelShadow panelShadow2;
    // End of variables declaration//GEN-END:variables
}
